#!/usr/bin/python
# -*- coding: utf-8 -*-
""" bitbucket_group_management module """

# Copyright: (c) 2018, Terry Jones <terry.jones@example.org>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

DOCUMENTATION = r'''
---
module: bitbucket_group_management
short_description: Manage groups in Bitbucket Cloud
version_added: "1.0.0"
description:
    - Create, update, and delete groups in a Bitbucket Cloud workspace.
    - Manage group membership by adding or removing members.
    - Uses the Bitbucket Cloud REST API v1, which is temporarily maintained
      for group management while the Atlassian platform completes its migration.
notes:
    - Group slugs are auto-generated by Bitbucket from the group name by
      converting spaces to dashes and lowercasing all characters.
      For example, C(My Group) becomes C(my-group).
    - Authentication requires an app password with Account and Group admin scopes.
options:
    username:
        description:
            - Username used for authentication.
        type: str
        required: true
    password:
        description:
            - App password used for authentication.
        type: str
        required: true
    workspace:
        description:
            - The workspace ID (slug) that owns the group.
        type: str
        required: true
    name:
        description:
            - The display name of the group.
            - Required when C(state=present).
        type: str
        required: false
    slug:
        description:
            - The group slug (identifier) used to look up an existing group.
            - When omitted the slug is derived from C(name) by replacing spaces
              with dashes and lowercasing.
            - Useful when C(state=absent) and the group name is not known.
        type: str
        required: false
    permission:
        description:
            - Default permission automatically granted to the group on all
              newly created repositories in the workspace.
        type: str
        choices: [ read, write, admin ]
        required: false
    repo_permissions:
        description:
            - List of repositories and the privilege level the group should
              have on each of them.
            - The module reconciles permissions to exactly match this list —
              missing privileges are added, out-of-date ones are updated, and
              privileges on repositories not in the list are revoked.
            - When omitted (C(null)), existing repository permissions are left
              unchanged.
            - Pass an empty list C([]) to revoke all existing repository
              permissions.
        type: list
        elements: dict
        required: false
        default: null
        suboptions:
            repository:
                type: str
                description:
                    - Repository slug.
                required: true
            privilege:
                type: str
                description:
                    - Privilege level to grant the group on the repository.
                choices: [ read, write, admin ]
                required: true
    members:
        description:
            - Desired list of account UUIDs to maintain as group members.
            - UUIDs must include curly braces, e.g. C({c423e13e-b541-3e77-b363-3e0b458u8226}).
            - The module reconciles membership to exactly match this list —
              missing members are added and extra members are removed.
            - When omitted, existing membership is left unchanged.
        type: list
        elements: str
        required: false
        default: []
    state:
        description:
            - C(present) ensures the group exists and is configured as specified.
            - C(absent) ensures the group does not exist.
        type: str
        choices: [ present, absent ]
        default: present
        required: false
author:
    - IT I2B (it@i2btech.com)
'''

EXAMPLES = r'''
- name: "Create a developers group with write permission and repo access"
  i2btech.ops.bitbucket_group_management:
    username: "alice"
    password: "app_password"
    workspace: "my-workspace"
    name: "Developers"
    permission: "write"
    members:
      - "{c423e13e-b541-3e77-b363-3e0b458u8226}"
      - "{b8441b1d-a5e6-480a-ba0b-fde829182e4a}"
    repo_permissions:
      - repository: "backend-api"
        privilege: "write"
      - repository: "frontend-app"
        privilege: "read"
    state: present

- name: "Update group permission to admin, keep repo permissions unchanged"
  i2btech.ops.bitbucket_group_management:
    username: "alice"
    password: "app_password"
    workspace: "my-workspace"
    name: "Developers"
    permission: "admin"
    state: present

- name: "Grant group access to a single repo (reconcile to only that repo)"
  i2btech.ops.bitbucket_group_management:
    username: "alice"
    password: "app_password"
    workspace: "my-workspace"
    name: "Developers"
    repo_permissions:
      - repository: "backend-api"
        privilege: "admin"
    state: present

- name: "Revoke all repository permissions for the group"
  i2btech.ops.bitbucket_group_management:
    username: "alice"
    password: "app_password"
    workspace: "my-workspace"
    name: "Developers"
    repo_permissions: []
    state: present

- name: "Remove a group"
  i2btech.ops.bitbucket_group_management:
    username: "alice"
    password: "app_password"
    workspace: "my-workspace"
    slug: "developers"
    state: absent
'''

RETURN = r'''
changed:
    description: Whether any change was made to the group, its membership, or its repository permissions.
    type: bool
    returned: always
group:
    description: The current state of the group after the module ran.
    type: dict
    returned: when state is present and the group exists
    sample:
        name: "Developers"
        slug: "developers"
        permission: "write"
        members: []
repo_permissions:
    description: List of repository privilege objects that are currently set for the group.
    type: list
    returned: when state is present and repo_permissions is provided
    sample:
        - repo: "my-workspace/backend-api"
          privilege: "write"
'''

# pylint: disable=wrong-import-position
from ansible_collections.i2btech.ops.plugins.module_utils.bitbucket import BitbucketHelper
from ansible.module_utils.basic import AnsibleModule
# pylint: enable=wrong-import-position


def _slugify(name):
    """Derive a Bitbucket group slug from a display name."""
    return name.lower().replace(' ', '-')


def run_module():
    """ main module """

    module_args = BitbucketHelper.bitbucket_argument_spec()
    module_args.update(
        workspace=dict(
            type='str',
            required=True,
            no_log=False),
        name=dict(
            type='str',
            required=False,
            no_log=False),
        slug=dict(
            type='str',
            required=False,
            no_log=False),
        permission=dict(
            type='str',
            required=False,
            choices=['read', 'write', 'admin']),
        repo_permissions=dict(
            type='list',
            elements='dict',
            required=False,
            default=None,
            options=dict(
                repository=dict(type='str', required=True),
                privilege=dict(
                    type='str',
                    required=True,
                    choices=['read', 'write', 'admin']),
            )),
        members=dict(
            type='list',
            elements='str',
            required=False,
            default=[]),
        state=dict(
            type='str',
            choices=['present', 'absent'],
            default='present'),
    )

    result = dict(
        changed=False,
        group={},
        repo_permissions=[],
    )

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
        required_if=[
            ('state', 'present', ['name']),
        ],
    )

    if module.check_mode:
        module.exit_json(**result)

    workspace = module.params['workspace']
    name = module.params['name']
    slug = module.params['slug'] or (_slugify(name) if name else None)
    permission = module.params['permission']
    members = module.params['members']
    repo_permissions = module.params['repo_permissions']
    state = module.params['state']

    if not slug:
        module.fail_json(msg="Either 'name' or 'slug' must be provided.")

    bitbucket = BitbucketHelper(module)

    existing_groups = bitbucket.get_groups(workspace)
    current_group = next(
        (g for g in existing_groups if g.get('slug') == slug),
        None
    )

    if state == 'present':
        if current_group is None:
            # Group does not exist — create it
            current_group = bitbucket.create_group(workspace, name)
            result['changed'] = True

            # Apply permission immediately after creation if requested
            if permission and current_group:
                current_group = bitbucket.update_group(
                    workspace,
                    current_group['slug'],
                    permission=permission,
                )
        else:
            # Group already exists — update name and/or permission if needed
            needs_update = False
            if name and current_group.get('name') != name:
                needs_update = True
            if permission and current_group.get('permission') != permission:
                needs_update = True

            if needs_update:
                update_kwargs = {}
                if name:
                    update_kwargs['name'] = name
                if permission:
                    update_kwargs['permission'] = permission
                current_group = bitbucket.update_group(
                    workspace,
                    current_group['slug'],
                    **update_kwargs
                )
                result['changed'] = True

        # Reconcile membership when the members list is explicitly provided
        if members is not None and current_group:
            actual_slug = current_group['slug']
            current_members = bitbucket.get_group_members(workspace, actual_slug)
            current_uuids = {m['uuid'] for m in current_members if 'uuid' in m}
            desired_uuids = set(members)

            for uuid in desired_uuids - current_uuids:
                bitbucket.add_group_member(workspace, actual_slug, uuid)
                result['changed'] = True

            for uuid in current_uuids - desired_uuids:
                bitbucket.remove_group_member(workspace, actual_slug, uuid)
                result['changed'] = True

        # Reconcile repository permissions when repo_permissions is explicitly set
        if repo_permissions is not None and current_group:
            actual_slug = current_group['slug']
            # group_owner is always the workspace in Bitbucket Cloud
            current_privs = bitbucket.get_group_repo_privileges(
                workspace, workspace, actual_slug
            )
            # Build a dict keyed by repo slug for quick lookup.
            # The 'repo' field from the API is in 'owner/repo-slug' format.
            current_map = {
                entry['repo'].split('/')[-1]: entry['privilege']
                for entry in current_privs
                if 'repo' in entry and 'privilege' in entry
            }
            desired_map = {
                rp['repository']: rp['privilege']
                for rp in repo_permissions
            }

            # Add or update
            for repo_slug, privilege in desired_map.items():
                if current_map.get(repo_slug) != privilege:
                    bitbucket.set_group_repo_privilege(
                        workspace, repo_slug, workspace, actual_slug, privilege
                    )
                    result['changed'] = True

            # Remove repos not in the desired list
            for repo_slug in current_map:
                if repo_slug not in desired_map:
                    bitbucket.delete_group_repo_privilege(
                        workspace, repo_slug, workspace, actual_slug
                    )
                    result['changed'] = True

            result['repo_permissions'] = bitbucket.get_group_repo_privileges(
                workspace, workspace, actual_slug
            )

        result['group'] = current_group or {}

    elif state == 'absent':
        if current_group is not None:
            bitbucket.delete_group(workspace, current_group['slug'])
            result['changed'] = True

    module.exit_json(**result)


def main():
    """ main function """
    run_module()


if __name__ == '__main__':
    main()
