- name: "Rotate logs"
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  pre_tasks:

    - name: Set facts
      ansible.builtin.set_fact:
        logs_directories_tmp: "{{ logs_directories.split(',') | list }}"
      changed_when: false

  roles:

    - role: i2btech.ops.logrotate
      host: "{{ lookup('ansible.builtin.file', '/etc/hostname') }}"
      service: "{{ service }}"
      logs_directories_list: "{{ logs_directories_tmp }}"
      s3_bucket_upload: "{{ s3_bucket | default('') }}"
      logrotate_delete_files_after_rotate: "{{ delete_files | default('FALSE') }}"
