---
logrotate_su_user: root
logrotate_dateext: "-%Y-%m-%d-%s"
logrotate_keep_for: 60 # logs are rotated this many times before deleted
logrotate_root: "/tmp/logrotate-ansible"
logrotate_conf: "{{ logrotate_root }}/logrotate.conf"
logrotate_delete_files_after_rotate: "FALSE"
