---
- name: Get timestamp
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: "Ensures rotated directory exists"
  ansible.builtin.file:
    path: "{{ logrotate_root }}/{{ item | replace('/', '_') }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ logs_directories_list }}"

- name: "Ensures logrotate config exists"
  ansible.builtin.template:
    src: "logrotate.j2.conf"
    dest: "{{ logrotate_conf }}"
    mode: "0644"

- name: "Rotate logs"
  ansible.builtin.command: "logrotate -f {{ logrotate_conf }}"
  register: my_output
  changed_when: my_output.rc == 0

- name: "Upload files to Bucket"
  community.aws.s3_sync:
    bucket: "{{ s3_bucket }}"
    key_prefix: "{{ service }}/{{ host }}/{{ item | replace('/', '_') }}"
    file_root: "{{ logrotate_root }}/{{ item | replace('/', '_') }}"
  with_items:
    - "{{ logs_directories_list }}"
  when: s3_bucket is defined
  become: false

- name: "Delete logrotate olddir"
  ansible.builtin.file:
    path: "{{ logrotate_root }}/{{ item | replace('/', '_') }}"
    state: absent
  with_items:
    - "{{ logs_directories_list }}"
  when: s3_bucket is defined
