---
name: Release Dockerhub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: i2btech/ansible-collection
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
          targets: playbooks
          push: true
          set: |
            *.tags=${{ steps.meta.outputs.tags }}
